"""
Sovereign-OS Compliance Frameworks
NIST CSF 2.0 + ISO 27001:2022 — Mapped to Sovereign-OS components
"""


def c(control_id, title, function, category, component, status, notes):
    return {
        "id": control_id,
        "title": title,
        "function": function,
        "category": category,
        "component": component,
        "status": status,
        "notes": notes,
    }


NIST_CSF2_CONTROLS = [
    # === GOVERN (GV) ===
    c("GV.OC-01", "The organizational mission is understood and informs cybersecurity risk management",
      "Govern", "Organizational Context", "workspace_management", "covered",
      "Workspace classification system maps organizational context and mission requirements"),
    c("GV.OC-02", "Internal and external stakeholders are understood",
      "Govern", "Organizational Context", "user_management", "partial",
      "User and device tracking covers internal stakeholders; external requires extension"),
    c("GV.OC-03", "Legal, regulatory, and contractual requirements are understood",
      "Govern", "Organizational Context", "compliance_mapper", "covered",
      "This compliance module maps regulatory requirements to controls"),
    c("GV.OC-04", "Critical objectives and cybersecurity requirements are understood",
      "Govern", "Organizational Context", "workspace_classification", "covered",
      "Workspace classification (PUBLIC, CONFIDENTIAL, TOP_SECRET) drives policy requirements"),
    c("GV.OC-05", "Outsourced services and supply chain risks are understood",
      "Govern", "Organizational Context", "none", "not_covered",
      "Supply chain risk management not yet implemented"),

    c("GV.RM-01", "Risk management objectives are established",
      "Govern", "Risk Management Strategy", "risk_engine", "covered",
      "Risk Engine evaluates multi-factor risk scores per session and user"),
    c("GV.RM-02", "Risk appetite and risk tolerance statements are established",
      "Govern", "Risk Management Strategy", "policy_engine", "covered",
      "Policy severity levels (CRITICAL, HIGH, MEDIUM, LOW) define risk tolerance"),
    c("GV.RM-03", "Org-wide risk activities are aligned with risk management strategy",
      "Govern", "Risk Management Strategy", "evidence_vault", "partial",
      "Evidence Vault tracks all events; risk alignment requires manual review"),

    c("GV.RR-01", "Organizational leadership is accountable for cybersecurity risk",
      "Govern", "Roles Responsibilities", "none", "not_applicable",
      "Organizational governance outside tool scope"),
    c("GV.RR-02", "Roles, responsibilities, and authorities are established",
      "Govern", "Roles Responsibilities", "access_grants", "partial",
      "Access grants and revocations are tracked per workspace"),

    c("GV.PO-01", "Organizational cybersecurity policy is established",
      "Govern", "Policy", "policy_engine", "covered",
      "Declarative YAML policy engine with 10 operators, wildcards, and priorities"),
    c("GV.PO-02", "Cybersecurity policy is communicated and enforced",
      "Govern", "Policy", "enforcement", "covered",
      "Policy Engine automatically enforces via FREEZE, ISOLATE, BLOCK actions"),

    c("GV.OV-01", "Risk management strategy is reviewed and adjusted",
      "Govern", "Oversight", "risk_engine", "partial",
      "Risk scores adjust in real-time; periodic review requires external process"),
    c("GV.OV-02", "Organizational cybersecurity strategy is reviewed",
      "Govern", "Oversight", "compliance_mapper", "partial",
      "Compliance gaps identified automatically; strategy review requires leadership"),

    c("GV.SC-01", "Cybersecurity supply chain risk management is established",
      "Govern", "Supply Chain Risk Mgmt", "none", "not_covered",
      "Supply chain risk management planned for Phase 3"),

    # === IDENTIFY (ID) ===
    c("ID.AM-01", "Inventories of hardware managed by the organization are maintained",
      "Identify", "Asset Management", "device_monitor", "covered",
      "USB Monitor tracks device serial numbers, classes, and connections"),
    c("ID.AM-02", "Inventories of software and services are maintained",
      "Identify", "Asset Management", "none", "not_covered",
      "Software inventory not yet implemented; planned for Phase 2"),
    c("ID.AM-03", "Representations of the organization network are maintained",
      "Identify", "Asset Management", "network_monitor", "partial",
      "Network Monitor tracks active connections via /proc/net/tcp"),
    c("ID.AM-04", "External systems and services are catalogued",
      "Identify", "Asset Management", "network_monitor", "partial",
      "External IP connections detected; full cataloguing requires enrichment"),
    c("ID.AM-05", "Resources are prioritized based on classification and business value",
      "Identify", "Asset Management", "workspace_classification", "covered",
      "Workspace classification (PUBLIC/CONFIDENTIAL/TOP_SECRET) drives resource prioritization"),

    c("ID.RA-01", "Vulnerabilities in assets are identified",
      "Identify", "Risk Assessment", "none", "not_covered",
      "Vulnerability scanning not yet implemented"),
    c("ID.RA-02", "Threat intelligence is received and acted upon",
      "Identify", "Risk Assessment", "risk_engine", "partial",
      "Risk Engine factors in threat indicators; full TI integration planned"),
    c("ID.RA-03", "Internal and external threats are identified",
      "Identify", "Risk Assessment", "risk_engine", "covered",
      "Risk Engine scores multi-factor threats: volume, timing, workspace, history"),
    c("ID.RA-04", "Potential impacts of identified threats are understood",
      "Identify", "Risk Assessment", "risk_engine", "covered",
      "Risk scoring quantifies potential impact from 0.0 to 1.0"),
    c("ID.RA-05", "Threats, vulnerabilities, likelihoods, and impacts are used for risk determination",
      "Identify", "Risk Assessment", "risk_engine", "covered",
      "Multi-factor risk calculation combines all variables"),
    c("ID.RA-06", "Risk responses are selected, prioritized, and tracked",
      "Identify", "Risk Assessment", "policy_engine", "covered",
      "Policy priorities (0-200) determine response precedence"),
    c("ID.RA-07", "Changes and exceptions are managed for risk",
      "Identify", "Risk Assessment", "policy_engine", "partial",
      "Policy toggle enables/disables; full exception management needs extension"),
    c("ID.RA-09", "Asset integrity is verified",
      "Identify", "Risk Assessment", "evidence_vault", "covered",
      "SHA-256 hashing + HMAC verification + Merkle tree integrity"),

    c("ID.IM-01", "Improvements are identified from evaluations",
      "Identify", "Improvement", "compliance_mapper", "covered",
      "Compliance gap analysis identifies improvement areas automatically"),
    c("ID.IM-02", "Improvements are identified from security tests and exercises",
      "Identify", "Improvement", "compliance_mapper", "covered",
      "Test suite (74 tests) validates security controls continuously"),
    c("ID.IM-03", "Improvements from incident lessons are identified",
      "Identify", "Improvement", "forensic_cases", "partial",
      "Forensic cases capture incident data; lesson integration requires manual process"),

    # === PROTECT (PR) ===
    c("PR.AA-01", "Identities and credentials are issued and managed",
      "Protect", "Identity Mgmt Auth Access", "user_management", "covered",
      "User and device identity tracked per session and event"),
    c("PR.AA-03", "Users are authenticated",
      "Protect", "Identity Mgmt Auth Access", "session_monitor", "covered",
      "Session Monitor tracks active user, display, and environment"),
    c("PR.AA-05", "Access permissions and authorizations are managed",
      "Protect", "Identity Mgmt Auth Access", "access_grants", "covered",
      "AccessGrant and Revocation entities with full audit trail"),

    c("PR.DS-01", "Data at rest is protected",
      "Protect", "Data Security", "evidence_vault", "covered",
      "Evidence Vault: SHA-256 + HMAC-SHA256 + Merkle tree + Ed25519 signatures"),
    c("PR.DS-02", "Data in transit is protected",
      "Protect", "Data Security", "hmac_verification", "covered",
      "All events signed with HMAC-SHA256; server verifies authenticity on ingest"),
    c("PR.DS-10", "Data in use is protected",
      "Protect", "Data Security", "workspace_isolation", "partial",
      "Workspace isolation restricts access; full data-in-use protection needs DRM"),
    c("PR.DS-11", "Backups of data are maintained and tested",
      "Protect", "Data Security", "merkle_tree", "covered",
      "Merkle tree epochs provide immutable backup of all event data"),

    c("PR.PS-01", "Configuration management is established",
      "Protect", "Platform Security", "agent_config", "partial",
      "Agent TOML config manages settings; enterprise config management needed"),
    c("PR.PS-03", "Software integrity is verified",
      "Protect", "Platform Security", "evidence_vault", "covered",
      "Ed25519 signatures verify data integrity at epoch level"),
    c("PR.PS-04", "Adequate logging records are generated",
      "Protect", "Platform Security", "event_logging", "covered",
      "Every event logged with 14 fields: type, payload, hash, hmac, severity, timestamp"),
    c("PR.PS-05", "Installation and execution of unauthorized software is prevented",
      "Protect", "Platform Security", "policy_engine", "covered",
      "Policy Engine blocks unauthorized actions via declarative rules"),

    c("PR.IR-01", "Networks are protected",
      "Protect", "Tech Infrastructure Resilience", "network_monitor", "covered",
      "Network Monitor + ISOLATE action (iptables DROP) provides network protection"),
    c("PR.IR-02", "The organization IT assets are protected",
      "Protect", "Tech Infrastructure Resilience", "usb_monitor", "covered",
      "USB Monitor + Filesystem Monitor + enforcement protects endpoints"),
    c("PR.IR-03", "Resilience mechanisms are implemented",
      "Protect", "Tech Infrastructure Resilience", "offline_queue", "covered",
      "JSONL offline queue + exponential backoff + batch sending ensures resilience"),

    # === DETECT (DE) ===
    c("DE.CM-01", "Networks and network services are monitored",
      "Detect", "Continuous Monitoring", "network_monitor", "covered",
      "Network Monitor polls /proc/net/tcp every 3 seconds, detects all connections"),
    c("DE.CM-03", "Personnel activity is monitored",
      "Detect", "Continuous Monitoring", "session_monitor", "covered",
      "Session Monitor tracks user changes, login/logout events in real-time"),
    c("DE.CM-07", "Monitoring for unauthorized activities is performed",
      "Detect", "Continuous Monitoring", "all_monitors", "covered",
      "4 monitors (USB, network, filesystem, session) provide comprehensive coverage"),
    c("DE.CM-09", "Computing hardware and software are inventoried",
      "Detect", "Continuous Monitoring", "device_monitor", "partial",
      "USB devices inventoried; full hardware/software inventory needs extension"),

    c("DE.AE-02", "Events are analyzed to understand attack targets and methods",
      "Detect", "Adverse Event Analysis", "risk_engine", "covered",
      "Risk Engine correlates events and scores threat level per session"),
    c("DE.AE-03", "Information from multiple sources is correlated",
      "Detect", "Adverse Event Analysis", "risk_engine", "covered",
      "Risk Engine combines USB, network, filesystem, and session data"),
    c("DE.AE-04", "Estimated impact of adverse events is determined",
      "Detect", "Adverse Event Analysis", "risk_engine", "covered",
      "Risk score 0.0-1.0 quantifies impact; triggers enforcement at thresholds"),
    c("DE.AE-06", "Information on adverse events is shared",
      "Detect", "Adverse Event Analysis", "alert_system", "covered",
      "Alert entity with severity levels, resolution tracking, and REST API"),
    c("DE.AE-07", "Incident data and metadata are analyzed",
      "Detect", "Adverse Event Analysis", "forensic_cases", "covered",
      "ForensicCase entity aggregates related events for investigation"),

    # === RESPOND (RS) ===
    c("RS.MA-01", "The incident response plan is executed",
      "Respond", "Incident Management", "enforcement", "covered",
      "Automatic enforcement: FREEZE (screen lock), ISOLATE (iptables), BLOCK"),
    c("RS.MA-02", "Incident reports are triaged and validated",
      "Respond", "Incident Management", "alert_system", "covered",
      "Alert triage via severity levels and policy priority matching"),
    c("RS.MA-03", "Incidents are categorized and prioritized",
      "Respond", "Incident Management", "alert_system", "covered",
      "Policy Engine assigns severity and priority to each detected incident"),
    c("RS.MA-05", "Criteria for initiating incident response are established",
      "Respond", "Incident Management", "policy_engine", "covered",
      "Policy triggers define exact criteria for automated response"),

    c("RS.AN-03", "Analysis is performed to determine incident timeline",
      "Respond", "Incident Analysis", "forensic_cases", "partial",
      "Event timestamps provide timeline; full correlation needs Phase 2 timeline view"),
    c("RS.AN-04", "Forensic analysis is performed",
      "Respond", "Incident Analysis", "evidence_vault", "covered",
      "Evidence Vault provides cryptographic proof chain for forensic analysis"),
    c("RS.AN-06", "Actions to contain the incident are determined and executed",
      "Respond", "Incident Analysis", "enforcement", "covered",
      "Enforcement executes containment automatically within milliseconds"),
    c("RS.AN-07", "Incident data and metadata are collected",
      "Respond", "Incident Analysis", "evidence_vault", "covered",
      "All event data sealed with SHA-256, HMAC, and Merkle position"),

    c("RS.MI-01", "Incidents are contained",
      "Respond", "Incident Mitigation", "enforcement_isolate", "covered",
      "ISOLATE action: iptables DROP all outbound except server connection"),
    c("RS.MI-02", "Incidents are eradicated",
      "Respond", "Incident Mitigation", "enforcement_isolate", "covered",
      "ISOLATE + process kill prevents further damage; evidence preserved"),

    c("RS.CO-02", "Internal and external stakeholders are notified",
      "Respond", "Response Reporting", "alert_system", "partial",
      "Internal alerts via API; external notification requires integration"),

    # === RECOVER (RC) ===
    c("RC.RP-01", "The recovery portion of the incident response plan is executed",
      "Recover", "Incident Recovery", "none", "not_covered",
      "Recovery automation planned for Phase 3"),
    c("RC.RP-02", "Recovery actions are selected, scoped, prioritized, and performed",
      "Recover", "Incident Recovery", "none", "not_covered",
      "Recovery playbooks planned for Phase 3"),
    c("RC.RP-04", "Integrity of restored assets is verified",
      "Recover", "Incident Recovery", "evidence_vault", "partial",
      "Evidence Vault can verify pre-incident state; automated restore needs Phase 3"),
    c("RC.CO-03", "Recovery activities are communicated",
      "Recover", "Recovery Communication", "none", "not_covered",
      "Recovery communication planned for Phase 3"),
]


ISO_27001_CONTROLS = [
    # === A.5 Organizational Controls ===
    c("A.5.1", "Policies for information security", "A.5 Organizational", "Policy",
      "policy_engine", "covered", "Declarative YAML policies with 10 operators"),
    c("A.5.2", "Information security roles and responsibilities", "A.5 Organizational", "Governance",
      "access_grants", "partial", "Access grants track roles; organizational RACI needs documentation"),
    c("A.5.3", "Segregation of duties", "A.5 Organizational", "Governance",
      "access_grants", "partial", "Workspace-level access control; fine-grained segregation needs extension"),
    c("A.5.7", "Threat intelligence", "A.5 Organizational", "Risk Assessment",
      "risk_engine", "partial", "Risk Engine factors threat indicators; full TI feed integration planned"),
    c("A.5.9", "Inventory of information and associated assets", "A.5 Organizational", "Asset Management",
      "asset_management", "partial", "Asset entity tracks devices; full inventory needs extension"),
    c("A.5.10", "Acceptable use of information and assets", "A.5 Organizational", "Policy",
      "policy_engine", "covered", "Policies define acceptable use with automatic enforcement"),
    c("A.5.12", "Classification of information", "A.5 Organizational", "Data Protection",
      "workspace_classification", "covered", "Workspace classification: PUBLIC, CONFIDENTIAL, TOP_SECRET"),
    c("A.5.13", "Labelling of information", "A.5 Organizational", "Data Protection",
      "workspace_classification", "partial", "Workspace labels drive policy; document-level labels need Phase 2"),
    c("A.5.14", "Information transfer", "A.5 Organizational", "Data Protection",
      "evidence_vault", "covered", "All transfers signed with HMAC-SHA256 and sealed in Merkle tree"),
    c("A.5.15", "Access control", "A.5 Organizational", "Access Management",
      "access_grants", "covered", "AccessGrant entity with workspace-level permissions and revocation"),
    c("A.5.16", "Identity management", "A.5 Organizational", "Access Management",
      "session_monitor", "covered", "Session Monitor tracks user identity per session"),
    c("A.5.17", "Authentication information", "A.5 Organizational", "Access Management",
      "session_monitor", "partial", "Session authentication tracked; credential management needs extension"),
    c("A.5.18", "Access rights", "A.5 Organizational", "Access Management",
      "access_grants", "covered", "Grant/revoke access per workspace with full audit trail"),
    c("A.5.23", "Information security for cloud services", "A.5 Organizational", "Cloud Security",
      "on_premise", "covered", "Entirely on-premise by design; no cloud dependency"),
    c("A.5.24", "Information security incident management", "A.5 Organizational", "Incident Management",
      "policy_engine", "covered", "Policy Engine + enforcement automates incident management"),
    c("A.5.25", "Assessment and decision on information security events", "A.5 Organizational", "Incident Management",
      "alert_system", "covered", "Events evaluated against policies, scored by risk engine"),
    c("A.5.26", "Response to information security incidents", "A.5 Organizational", "Incident Management",
      "enforcement", "covered", "FREEZE, ISOLATE, BLOCK actions executed automatically"),
    c("A.5.27", "Learning from information security incidents", "A.5 Organizational", "Incident Management",
      "forensic_cases", "partial", "ForensicCases capture incidents; lesson integration needs process"),
    c("A.5.28", "Collection of evidence", "A.5 Organizational", "Forensics",
      "evidence_vault", "covered", "SHA-256 + HMAC + Merkle + Ed25519 chain of custody"),
    c("A.5.29", "Information security during disruption", "A.5 Organizational", "Resilience",
      "offline_queue", "covered", "JSONL offline queue ensures no events lost during disruption"),
    c("A.5.31", "Legal and regulatory requirements", "A.5 Organizational", "Compliance",
      "compliance_mapper", "covered", "This module: NIST CSF 2.0 + ISO 27001 mapping"),
    c("A.5.33", "Protection of records", "A.5 Organizational", "Records Management",
      "evidence_vault", "covered", "All records sealed with cryptographic proof"),
    c("A.5.35", "Independent review of information security", "A.5 Organizational", "Audit",
      "compliance_mapper", "partial", "Automated gap analysis; full independent review needs external audit"),
    c("A.5.36", "Compliance with policies, rules and standards", "A.5 Organizational", "Compliance",
      "compliance_mapper", "covered", "Compliance mapping evaluates control coverage automatically"),

    # === A.6 People Controls ===
    c("A.6.1", "Screening", "A.6 People", "HR Security",
      "none", "not_covered", "Background screening outside tool scope"),
    c("A.6.3", "Information security awareness, education and training", "A.6 People", "Training",
      "none", "not_covered", "Training management planned for Phase 3"),
    c("A.6.7", "Remote working", "A.6 People", "Remote Work",
      "session_monitor", "partial", "Session and network monitoring covers remote endpoints"),
    c("A.6.8", "Information security event reporting", "A.6 People", "Event Reporting",
      "alert_system", "covered", "All events reported via alert system with severity classification"),

    # === A.7 Physical Controls ===
    c("A.7.10", "Storage media", "A.7 Physical", "Media Handling",
      "usb_monitor", "covered", "USB Monitor detects, classifies, and blocks storage devices"),
    c("A.7.11", "Supporting utilities", "A.7 Physical", "Physical Security",
      "none", "not_applicable", "Physical infrastructure monitoring outside tool scope"),
    c("A.7.14", "Secure disposal or re-use of equipment", "A.7 Physical", "Equipment",
      "none", "not_applicable", "Physical disposal outside tool scope"),

    # === A.8 Technological Controls ===
    c("A.8.1", "User endpoint devices", "A.8 Technological", "Endpoint Security",
      "usb_monitor", "covered", "USB + filesystem + session monitoring per endpoint"),
    c("A.8.2", "Privileged access rights", "A.8 Technological", "Access Management",
      "access_grants", "covered", "Privileged access tracked and revocable per workspace"),
    c("A.8.3", "Information access restriction", "A.8 Technological", "Access Management",
      "policy_engine", "covered", "Policy Engine restricts access based on classification and rules"),
    c("A.8.4", "Access to source code", "A.8 Technological", "Code Security",
      "workspace_isolation", "covered", "Workspace isolation controls source code access"),
    c("A.8.5", "Secure authentication", "A.8 Technological", "Authentication",
      "session_monitor", "partial", "Session tracking active; MFA integration planned"),
    c("A.8.7", "Protection against malware", "A.8 Technological", "Malware Protection",
      "filesystem_monitor", "partial", "Detects ransomware patterns (.locked, .encrypted, .crypto)"),
    c("A.8.9", "Configuration management", "A.8 Technological", "Configuration",
      "agent_config", "partial", "Agent TOML config; enterprise config management needs extension"),
    c("A.8.12", "Data leakage prevention", "A.8 Technological", "DLP",
      "policy_engine", "covered", "USB blocking + network monitoring + file access policies"),
    c("A.8.13", "Information backup", "A.8 Technological", "Backup",
      "merkle_tree", "partial", "Merkle tree provides integrity verification; full backup needs Phase 2"),
    c("A.8.15", "Logging", "A.8 Technological", "Logging",
      "event_logging", "covered", "All events logged with 14 fields, signed, and sealed"),
    c("A.8.16", "Monitoring activities", "A.8 Technological", "Monitoring",
      "all_monitors", "covered", "4 independent monitors: USB, network, filesystem, session"),
    c("A.8.20", "Networks security", "A.8 Technological", "Network Security",
      "network_monitor", "covered", "Network Monitor + ISOLATE provides network security"),
    c("A.8.21", "Security of network services", "A.8 Technological", "Network Security",
      "network_monitor", "covered", "Connection monitoring detects suspicious network services"),
    c("A.8.22", "Segregation of networks", "A.8 Technological", "Network Security",
      "enforcement_isolate", "covered", "ISOLATE action: iptables network segregation"),
    c("A.8.24", "Use of cryptography", "A.8 Technological", "Cryptography",
      "evidence_vault", "covered", "SHA-256, HMAC-SHA256, Merkle tree, Ed25519"),
    c("A.8.32", "Change management", "A.8 Technological", "Change Management",
      "policy_engine", "partial", "Policy toggle for controlled changes; full change management needs process"),


]

# === Helper Functions ===

def get_nist_csf2():
    return {
        "name": "NIST CSF 2.0",
        "version": "2.0",
        "description": "NIST Cybersecurity Framework 2.0 — Functions: Govern, Identify, Protect, Detect, Respond, Recover",
        "source": "https://www.nist.gov/cyberframework",
        "controls": NIST_CSF2_CONTROLS,
    }


def get_iso_27001():
    return {
        "name": "ISO 27001:2022",
        "version": "2022",
        "description": "ISO/IEC 27001:2022 Annex A — Themes: Organizational, People, Physical, Technological",
        "source": "https://www.iso.org/standard/27001",
        "controls": ISO_27001_CONTROLS,
    }




# === SOC 2 Type II ===
SOC2_CONTROLS = [
    c("CC1.1", "Management demonstrates integrity and ethical values", "CC1", "Control Environment",
      "policy_engine", "covered", "Policy engine enforces organizational values through automated rules"),
    c("CC1.2", "Board exercises oversight of internal controls", "CC1", "Control Environment",
      "compliance_mapper", "partial", "Compliance reporting provides board-level visibility"),
    c("CC1.3", "Management establishes authority and responsibility", "CC1", "Control Environment",
      "access_grants", "covered", "Access grants define authority with workspace-level granularity"),
    c("CC1.4", "Competence commitment is demonstrated", "CC1", "Control Environment",
      "none", "not_applicable", "HR process outside tool scope"),
    c("CC1.5", "Accountability for internal controls is enforced", "CC1", "Control Environment",
      "evidence_vault", "covered", "All actions signed and sealed with immutable evidence"),

    c("CC2.1", "Internal control information is generated", "CC2", "Communication",
      "event_logging", "covered", "All events logged with 14 fields, signed, and sealed"),
    c("CC2.2", "Internal control information is communicated internally", "CC2", "Communication",
      "alert_system", "covered", "Alert system communicates control violations to stakeholders"),
    c("CC2.3", "Communication with external parties", "CC2", "Communication",
      "alert_system", "partial", "Internal alerts complete; external notification needs integration"),

    c("CC3.1", "Risk assessment considers objectives", "CC3", "Risk Assessment",
      "risk_engine", "covered", "Risk Engine evaluates multi-factor risk against business objectives"),
    c("CC3.2", "Risk of fraud is considered", "CC3", "Risk Assessment",
      "risk_engine", "covered", "User history and anomaly detection identify fraud indicators"),
    c("CC3.3", "Significant changes are identified", "CC3", "Risk Assessment",
      "filesystem_monitor", "covered", "Filesystem Monitor detects significant file changes"),
    c("CC3.4", "Fraud risk factors are identified", "CC3", "Risk Assessment",
      "risk_engine", "covered", "Multi-factor risk scoring identifies fraud patterns"),

    c("CC4.1", "Ongoing and separate evaluations are performed", "CC4", "Monitoring",
      "all_monitors", "covered", "4 continuous monitors provide ongoing evaluation"),
    c("CC4.2", "Internal control deficiencies are communicated", "CC4", "Monitoring",
      "alert_system", "covered", "Alert system communicates deficiencies with severity classification"),

    c("CC5.1", "Management designs control activities", "CC5", "Control Activities",
      "policy_engine", "covered", "Declarative YAML policies define control activities"),
    c("CC5.2", "Technology general controls are deployed", "CC5", "Control Activities",
      "enforcement", "covered", "Enforcement actions (FREEZE/ISOLATE/BLOCK) deploy controls"),
    c("CC5.3", "Policies and procedures are implemented", "CC5", "Control Activities",
      "policy_engine", "covered", "Policies loaded from YAML, evaluated against every event"),

    c("CC6.1", "Logical access controls are implemented", "CC6", "Logical Access",
      "access_grants", "covered", "Access grants with workspace-level permissions"),
    c("CC6.2", "Authentication mechanisms are implemented", "CC6", "Logical Access",
      "session_monitor", "covered", "Session Monitor tracks authenticated sessions"),
    c("CC6.3", "Access is restricted to authorized users", "CC6", "Logical Access",
      "policy_engine", "covered", "Policy engine blocks unauthorized access"),
    c("CC6.4", "Access to facilities is restricted", "CC6", "Logical Access",
      "usb_monitor", "partial", "Physical USB monitoring; facility access needs physical controls"),
    c("CC6.5", "Access is removed when no longer needed", "CC6", "Logical Access",
      "access_grants", "covered", "Revocation entity tracks access removal"),
    c("CC6.6", "Logical access security measures restrict access", "CC6", "Logical Access",
      "enforcement_isolate", "covered", "ISOLATE action restricts network access"),
    c("CC6.7", "Data transmission is restricted", "CC6", "Logical Access",
      "network_monitor", "covered", "Network Monitor detects and blocks unauthorized transmission"),
    c("CC6.8", "Unauthorized access is prevented", "CC6", "Logical Access",
      "all_monitors", "covered", "Comprehensive monitoring prevents unauthorized access"),

    c("CC7.1", "Detection and monitoring procedures are implemented", "CC7", "System Operations",
      "all_monitors", "covered", "USB, network, filesystem, and session monitors"),
    c("CC7.2", "Anomalies are identified and acted upon", "CC7", "System Operations",
      "risk_engine", "covered", "Risk Engine identifies anomalies and triggers enforcement"),
    c("CC7.3", "Incident response procedures are implemented", "CC7", "System Operations",
      "enforcement", "covered", "Automated incident response via FREEZE/ISOLATE/BLOCK"),
    c("CC7.4", "Incident response is recovery-oriented", "CC7", "System Operations",
      "forensic_cases", "partial", "Forensic cases capture incident data; recovery automation in Phase 3"),
    c("CC7.5", "Incident information is communicated", "CC7", "System Operations",
      "alert_system", "covered", "Alert system with severity classification and REST API"),

    c("CC8.1", "Changes are authorized, designed, and implemented", "CC8", "Change Management",
      "policy_engine", "partial", "Policy toggle for controlled changes; full change management needs process"),
    c("CC8.2", "Changes are authorized before deployment", "CC8", "Change Management",
      "policy_engine", "partial", "Policy versioning; deployment authorization needs CI/CD integration"),
    c("CC8.3", "Changes are tested and deployed", "CC8", "Change Management",
      "none", "not_covered", "CI/CD integration planned for Phase 3"),

    c("CC9.1", "Risk mitigation activities are identified", "CC9", "Risk Mitigation",
      "policy_engine", "covered", "Policies define risk mitigation through automated enforcement"),
    c("CC9.2", "Vendor and third-party risk is managed", "CC9", "Risk Mitigation",
      "none", "not_covered", "Third-party risk management planned for Phase 3"),
]

# === GDPR ===
GDPR_CONTROLS = [
    c("Art.5", "Principles relating to processing of personal data", "Chapter II", "Principles",
      "evidence_vault", "partial", "Data minimization through workspace classification; full DPIA needed"),
    c("Art.25", "Data protection by design and by default", "Chapter III", "Design",
      "workspace_isolation", "covered", "Workspace isolation and classification by design"),
    c("Art.28", "Processor obligations", "Chapter III", "Processor",
      "access_grants", "partial", "Access control for processors; full DPA management needed"),
    c("Art.30", "Records of processing activities", "Chapter III", "Records",
      "event_logging", "covered", "All data processing events logged and sealed"),
    c("Art.32", "Security of processing", "Chapter III", "Security",
      "evidence_vault", "covered", "SHA-256 + HMAC + Merkle + Ed25519 encryption chain"),
    c("Art.33", "Notification to supervisory authority", "Chapter III", "Breach",
      "breach_notification", "covered", "Automated breach detection and notification engine"),
    c("Art.34", "Communication to data subjects", "Chapter III", "Breach",
      "breach_notification", "partial", "Breach detection complete; subject notification needs integration"),
    c("Art.35", "Data protection impact assessment", "Chapter III", "DPIA",
      "compliance_mapper", "partial", "Risk assessment engine; formal DPIA template needed"),
    c("Art.44-49", "Transfers to third countries", "Chapter V", "Transfers",
      "network_monitor", "covered", "Network Monitor detects external data transfers"),
]

# === CMMC 2.0 ===
CMMC_CONTROLS = [
    c("AC.L1-3.1.1", "Limit system access to authorized users", "AC", "Access Control",
      "access_grants", "covered", "Access grants with workspace-level permissions"),
    c("AC.L1-3.1.2", "Limit system access to authorized transactions", "AC", "Access Control",
      "policy_engine", "covered", "Policy Engine limits access to authorized transactions"),
    c("AC.L1-3.1.20", "Verify and control external connections", "AC", "Access Control",
      "network_monitor", "covered", "Network Monitor verifies all external connections"),
    c("AC.L1-3.1.22", "Control information posted on public websites", "AC", "Access Control",
      "workspace_classification", "partial", "Workspace classification; public website control needs CMS integration"),
    c("AU.L1-3.3.1", "Create and retain audit records", "AU", "Audit",
      "evidence_vault", "covered", "All events retained in immutable Evidence Vault"),
    c("AU.L1-3.3.2", "Create and retain audit records for review", "AU", "Audit",
      "forensic_cases", "covered", "Forensic cases aggregate audit records"),
    c("IA.L1-3.5.1", "Identify system users", "IA", "Identification",
      "session_monitor", "covered", "Session Monitor identifies all active users"),
    c("IA.L1-3.5.2", "Authenticate system users", "IA", "Identification",
      "session_monitor", "covered", "Session authentication tracked"),
    c("MP.L1-3.8.3", "Sanitize or destroy media", "MP", "Media Protection",
      "usb_monitor", "partial", "USB monitoring detects media; sanitization needs wipe integration"),
    c("PE.L1-3.10.1", "Limit physical access to systems", "PE", "Physical",
      "usb_monitor", "partial", "USB physical access monitoring; facility access needs physical controls"),
    c("SC.L1-3.13.1", "Monitor and control communications at boundaries", "SC", "System Comms",
      "network_monitor", "covered", "Network Monitor controls communications at boundaries"),
    c("SC.L1-3.13.5", "Implement subnetworks for public systems", "SC", "System Comms",
      "enforcement_isolate", "covered", "ISOLATE creates network segmentation"),
    c("SI.L1-3.14.1", "Identify and manage flaws timely", "SI", "System Integrity",
      "filesystem_monitor", "partial", "Filesystem Monitor detects changes; vulnerability management needed"),
    c("SI.L1-3.14.2", "Malicious code protection", "SI", "System Integrity",
      "filesystem_monitor", "covered", "Detects ransomware patterns and malicious file operations"),
    c("SI.L1-3.14.4", "Malicious code protection update mechanism", "SI", "System Integrity",
      "policy_engine", "covered", "Policy updates deploy protection rules"),
    c("SI.L1-3.14.5", "Perform periodic scans", "SI", "System Integrity",
      "all_monitors", "covered", "Continuous scanning via 4 monitors"),
]

# === PCI DSS 4.0 ===
PCI_CONTROLS = [
    c("Req.1", "Install and maintain network security controls", "Network", "Network Security",
      "network_monitor", "covered", "Network Monitor + ISOLATE provides network security"),
    c("Req.2", "Apply secure configurations", "Configuration", "System Hardening",
      "agent_config", "partial", "Agent config management; full hardening needs CIS benchmarks"),
    c("Req.3", "Protect stored account data", "Data", "Data Protection",
      "evidence_vault", "partial", "Evidence Vault protects data; PCI-specific encryption for card data needed"),
    c("Req.4", "Protect cardholder data with strong cryptography during transmission", "Data", "Data Protection",
      "hmac_verification", "covered", "HMAC-SHA256 protects data in transit"),
    c("Req.5", "Protect from malicious software", "Software", "Malware",
      "filesystem_monitor", "covered", "Ransomware pattern detection"),
    c("Req.6", "Develop and maintain secure systems", "Development", "Secure Development",
      "evidence_vault", "partial", "Evidence integrity; secure SDLC needs CI/CD integration"),
    c("Req.7", "Restrict access by business need to know", "Access", "Access Control",
      "access_grants", "covered", "Workspace-based access with need-to-know classification"),
    c("Req.8", "Identify users and authenticate access", "Access", "Identity",
      "session_monitor", "covered", "Session Monitor identifies and authenticates users"),
    c("Req.9", "Restrict physical access to cardholder data", "Physical", "Physical Access",
      "usb_monitor", "partial", "USB monitoring; full physical access control needs facilities"),
    c("Req.10", "Log and monitor all access", "Logging", "Monitoring",
      "all_monitors", "covered", "4 monitors log all access with immutable evidence"),
    c("Req.11", "Test security regularly", "Testing", "Security Testing",
      "compliance_mapper", "partial", "Compliance gap analysis; penetration testing needs external service"),
    c("Req.12", "Support information security with policies", "Policy", "Security Policy",
      "policy_engine", "covered", "Declarative YAML policies support information security"),
]

# === HIPAA ===
HIPAA_CONTROLS = [
    c("§164.308(a)(1)", "Security management process", "Administrative", "Security Management",
      "risk_engine", "covered", "Risk Engine implements security management through risk analysis"),
    c("§164.308(a)(3)", "Workforce security", "Administrative", "Workforce",
      "access_grants", "covered", "Access grants enforce workforce security"),
    c("§164.308(a)(4)", "Information access management", "Administrative", "Access Management",
      "access_grants", "covered", "Workspace-level access management"),
    c("§164.308(a)(5)", "Security awareness and training", "Administrative", "Training",
      "none", "not_covered", "Training management planned for Phase 3"),
    c("§164.308(a)(6)", "Security incident procedures", "Administrative", "Incident",
      "enforcement", "covered", "Automated incident detection and response"),
    c("§164.308(a)(7)", "Contingency plan", "Administrative", "Contingency",
      "offline_queue", "partial", "Offline queue provides data resilience; full DR plan needed"),
    c("§164.308(a)(8)", "Evaluation", "Administrative", "Evaluation",
      "compliance_mapper", "covered", "Automated compliance evaluation"),
    c("§164.310(a)(1)", "Facility access controls", "Physical", "Facility",
      "none", "not_applicable", "Physical facility controls outside tool scope"),
    c("§164.310(d)(1)", "Device and media controls", "Physical", "Device Controls",
      "usb_monitor", "covered", "USB Monitor tracks device access and controls media"),
    c("§164.312(a)(1)", "Access control", "Technical", "Access Control",
      "access_grants", "covered", "Technical access control via access grants and policies"),
    c("§164.312(b)", "Audit controls", "Technical", "Audit",
      "evidence_vault", "covered", "Immutable audit trail with Merkle tree and Ed25519"),
    c("§164.312(c)", "Integrity", "Technical", "Integrity",
      "evidence_vault", "covered", "SHA-256 + HMAC integrity verification"),
    c("§164.312(d)", "Authentication", "Technical", "Authentication",
      "session_monitor", "covered", "Session Monitor tracks user authentication"),
    c("§164.312(e)(1)", "Transmission security", "Technical", "Transmission",
      "hmac_verification", "covered", "HMAC-SHA256 protects data in transit"),
]


def get_soc2():
    return {"name": "SOC 2 Type II", "version": "2017", "description": "SOC 2 Type II Trust Services Criteria",
            "source": "https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2",
            "controls": SOC2_CONTROLS}

def get_gdpr():
    return {"name": "GDPR", "version": "2016/679", "description": "General Data Protection Regulation",
            "source": "https://gdpr.eu", "controls": GDPR_CONTROLS}

def get_cmmc():
    return {"name": "CMMC 2.0", "version": "2.0", "description": "Cybersecurity Maturity Model Certification",
            "source": "https://dodcio.defense.gov/cmmc/", "controls": CMMC_CONTROLS}

def get_pci():
    return {"name": "PCI DSS 4.0", "version": "4.0", "description": "Payment Card Industry Data Security Standard",
            "source": "https://www.pcisecuritystandards.org/", "controls": PCI_CONTROLS}

def get_hipaa():
    return {"name": "HIPAA", "version": "2013", "description": "Health Insurance Portability and Accountability Act",
            "source": "https://www.hhs.gov/hipaa/index.html", "controls": HIPAA_CONTROLS}


def get_all_frameworks():
    return [get_nist_csf2(), get_iso_27001(), get_soc2(), get_gdpr(), get_cmmc(), get_pci(), get_hipaa()]


def get_framework(name):
    name_lower = name.lower().replace(" ", "").replace("-", "").replace("_", "").replace(".", "").replace(":", "")
    for fw in get_all_frameworks():
        fw_key = fw["name"].lower().replace(" ", "").replace("-", "").replace("_", "").replace(".", "").replace(":", "")
        if name_lower == fw_key or name_lower in fw_key or fw_key in name_lower:
            return fw
    return None
